//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2110181055_Scholar
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_scholarsEntities : DbContext
    {
        public db_scholarsEntities()
            : base("name=db_scholarsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<faculty> faculties { get; set; }
        public virtual DbSet<lecturer> lecturers { get; set; }
        public virtual DbSet<university> universities { get; set; }
    }
}
